# Onde os dados chegam
# Geralmente são: 
# • otlp → Protocolo do OpenTelemetry para .Net, Java, Node, etc
# • prometheus → recebe metricas via Http
# • jaeger → traces dele mesmo
# • outros → zipkin, filelog
receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http: #usado nas bibliotecas ou clientes que não suportam grpc
        endpoint: 0.0.0.0:4318

# Onde os dados são processados
# Geralmente são: 
# •	batch → junta os logs em pacotes para envio mais eficiente
#	•	attributes → adiciona ou renomeia campos
#	•	memory_limiter → protege a memória da fábrica
processors:
  batch:
    send_batch_size: 50          # quantos itens enviar por vez (default 512, melhor pra prod)
    timeout: 10s                 # tempo máximo de espera antes de enviar (default 5s)
    send_batch_max_size: 1000     # limite máximo do lote

# Para onde os dados vão
# mandam os logs para onde precisam chegar
exporters:
  elasticsearch:
    endpoint: ${ES_ENDPOINT}
    # pipeline: "otel-logs-pipeline"     # opcional: se criar ingest pipeline
    auth: 
      authenticator: basicauth
    # tls: #usado para https
    #   insecure_skip_verify: true  # DEV: ignora o self-signed do ES 8.x
    # Opcional: controle de batching do exporter (ele já tem o próprio)
    flush:
      bytes: 3145728   # ~3MB
      interval: 5s
    # Não funciona com elastic
    # sending_queue: #Essa seção ativa uma fila interna que armazena os dados antes de enviá-los. Isso ajuda a lidar com picos de carga ou lentidão no destino.
    #   enabled: true
    #   num_consumers: 4 #define quantos consumidores (threads internas) vão processar e enviar os dados da fila. Mais consumidores = mais paralelismo.
    #   queue_size: 5000 #Tamanho máximo da fila. Se a fila encher, os dados novos podem ser descartados 
    # retry_on_failure:
    #   enabled: true
    #   initial_interval: 5s
    #   max_interval: 30s
    #   max_elapsed_time: 15m
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 1  # imprime todos os logs após os 5 iniciais

# funcoes extras
# podem ser: 
# • basicauth: autenticação básica (usuário/senha).
# •	health_check: endpoint para saber se o Collector está vivo.
# •	pprof: expõe profiling.
# •	zpages: páginas web para debug.
# •	bearertokenauth: autenticação via token.
# •	oidc: autenticação com OpenID Connect.
extensions: 
  basicauth:
    client_auth:
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}
  health_check:
    endpoint: "0.0.0.0:13133"

service:
  extensions: [health_check, basicauth]
  
  # linha de produção
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
    
    metrics: 
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
    
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ elasticsearch, debug ]