name: CI - Git Flow (.NET 9)

on:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize, reopened]

  push:
    branches:
      - feat/*
      - feature/*
      - release/*
      - hotfix/*
      - bugfix/*
      - chore/*
      - docs/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Observabilidade.Api/Observabilidade.Api.csproj

      - name: Build
        run: dotnet build ./Observabilidade.Api/Observabilidade.Api.csproj --no-restore --configuration Release

      # - name: Run tests
      #   run: dotnet test ./Observabilidade.Api/Observabilidade.Api.csproj --no-build --verbosity normal
