name: Publish Estudos.Common Package

on:
  push:
    tags:
      - 'v*.*.*' # Ex: v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./Estudos.Common/Estudos.Common.csproj

      - name: Build
        run: dotnet build ./Estudos.Common/Estudos.Common.csproj --configuration Release

      - name: Pack NuGet
        run: dotnet pack ./Estudos.Common/Estudos.Common.csproj \
          --configuration Release \
          --output ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push "./artifacts/*.nupkg" \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"