name: Test - NuGet Restore
on:
  workflow_dispatch:
jobs:
  restore:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Add NuGet Sources
        run: |
          dotnet nuget remove source github || true && \
          dotnet nuget remove source nuget.org || true && \
          dotnet nuget add source --name github "https://nuget.pkg.github.com/danibrdev/index.json" \
          --username danibrdev \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text 
      - name: Restore Dependencies
        run: dotnet restore ./Observabilidade.Api/Observabilidade.Api.csproj